### ISSUE TITLE
General Questions- Ideas

### ISSUE THREAD

**Issue by harunaltunhr** [harunaltunhr/duck-duck-clone#2]
Hello Ladies

-We can discuss our topics and ideas in this issue.

1. Will we need a global container, or not? I inspect website I didn't find useful area for container(global), so is it important? Will you want to create one? If yes  where will we use. ( I added sth in body)

**Comment by adekimpianna** [comment]
You are right. If it’s not needed now, no need to make it. If after all is finished and we think that we need it, we can still add it on the step of Final Touches, right?

**Comment by harunaltunhr** [comment]
Could you please look navbar?

https://htmlpreview.github.io/?https://github.com/harunaltunhr/duck-duck-clone/blob/nav-bar/index.html

**Comment by adekimpianna** [comment]
@harunaltunhr for me it is actually good! 

Is there still a way to make the writing not so close to the border?
![afbeelding](https://user-images.githubusercontent.com/62487749/83693169-d0fc7d00-a5f5-11ea-8df6-b00a915344b1.png)

**Comment by Boam1994** [comment]
Maybe you can add some padding on left & right?

**Comment by Boam1994** [comment]
I get blocked to create my second branch "instructions" next to the basic master. Any idea?
If not i'm going to wait for Stephane call at 12

**Comment by harunaltunhr** [comment]
Goodnight ladies, I created a new branch as you see and merged all branches in that new branch to see how webpage looks :) Yeah it will be great :+1: 


https://github.com/harunaltunhr/duck-duck-clone/blob/Merged-Branchees/index.html

**Comment by harunaltunhr** [comment]
@Boam1994 in Specialities section you have one ul code. You need to add class name because it change all ul in page
 (***.enumaration***)ul{
    display: flex;
    flex-direction: row;
    justify-content: center;
    list-style: none;
}

**Comment by adekimpianna** [comment]
@Boam1994 @harunaltunhr Thank youuu for your hard work guys!!! our project has completed, it is done!!! 😆 I will close this issue too
